# basic java workflow
name: Java CI with Maven

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ cicd ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java/starter

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'
    - name: Print Java version
      run: java -version
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test with Maven
      run: mvn test
