# basic java workflow
name: Python application

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ cicd ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./java/passchecker
    
    steps:

    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Print Python version
      run: python --version

    - name: Install dependencies
      run: echo "installing dependencies"

    - name: Run tests
      run: pytest